### ISSUE TITLE
Error on sync

### ISSUE THREAD

**Issue by Leemoonsoo** [luna-ml/luna#78]
```
FO:Flask-Cors:CORS request from Origin:None, setting Access-Control-Allow-Origin:*
luna-7995d99d9b-lbwns luna INFO:werkzeug:10.140.15.199 - - [06/Apr/2021 00:53:57] "GET /socket.io/?EIO=4&transport=polling&t=NYagyBl&sid=C4fnaHMg6RIqK8IGAAAQ HTTP/1.1" 200 -
luna-7995d99d9b-lbwns luna INFO:werkzeug:10.140.15.196 - - [06/Apr/2021 00:53:57] "POST /v1/project HTTP/1.1" 200 -
luna-7995d99d9b-lbwns luna INFO:Flask-Cors:CORS request from Origin:None, setting Access-Control-Allow-Origin:*
luna-7995d99d9b-lbwns luna INFO:werkzeug:10.140.0.49 - - [06/Apr/2021 00:53:57] "POST /v1/project/1/model HTTP/1.1" 200 -
luna-7995d99d9b-lbwns luna ERROR:api.model_api:(psycopg2.errors.GroupingError) column "evaluation.id" must appear in the GROUP BY clause or be used in an aggregate function
luna-7995d99d9b-lbwns luna LINE 3: FROM evaluation, (SELECT evaluation.id AS id, evaluation.nam...
luna-7995d99d9b-lbwns luna                                  ^
luna-7995d99d9b-lbwns luna 
luna-7995d99d9b-lbwns luna [SQL: SELECT r1.id AS r1_id, r1.model_id AS r1_model_id, r1.project_rev_id AS r1_project_rev_id, r1.name AS r1_name, r1.output_path AS r1_output_path, r1.exit_code AS r1_exit_code, r1.created_at AS r1_created_at, r1.finished_at AS r1_finished_at 
luna-7995d99d9b-lbwns luna FROM (SELECT evaluation.id AS id, evaluation.model_id AS model_id, evaluation.project_rev_id AS project_rev_id, evaluation.name AS name, evaluation.output_path AS output_path, evaluation.exit_code AS exit_code, evaluation.created_at AS created_at, evaluation.finished_at AS finished_at 
luna-7995d99d9b-lbwns luna FROM evaluation, (SELECT evaluation.id AS id, evaluation.name AS name, max(evaluation.id) AS max_id 
luna-7995d99d9b-lbwns luna FROM evaluation GROUP BY evaluation.model_id, evaluation.name) AS e2 
luna-7995d99d9b-lbwns luna WHERE evaluation.model_id = %(model_id_1)s AND evaluation.id = e2.max_id) AS r1]
luna-7995d99d9b-lbwns luna [parameters: {'model_id_1': 1}]
luna-7995d99d9b-lbwns luna (Background on this error at: http://sqlalche.me/e/13/f405)
luna-7995d99d9b-lbwns luna ERROR:server.main_handler:Exception on /v1/project/1/model/1/eval [POST]
luna-7995d99d9b-lbwns luna Traceback (most recent call last):
luna-7995d99d9b-lbwns luna   File "/home/luna/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
luna-7995d99d9b-lbwns luna     cursor, statement, parameters, context
luna-7995d99d9b-lbwns luna   File "/home/luna/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
luna-7995d99d9b-lbwns luna     cursor.execute(statement, parameters)
luna-7995d99d9b-lbwns luna psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block
luna-7995d99d9b-lbwns luna 
luna-7995d99d9b-lbwns luna 
luna-7995d99d9b-lbwns luna The above exception was the direct cause of the following exception:
luna-7995d99d9b-lbwns luna 
luna-7995d99d9b-lbwns luna Traceback (most recent call last):
luna-7995d99d9b-lbwns luna   File "/home/luna/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
luna-7995d99d9b-lbwns luna     response = self.full_dispatch_request()
luna-7995d99d9b-lbwns luna   File "/home/luna/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
luna-7995d99d9b-lbwns luna     rv = self.handle_user_exception(e)
luna-7995d99d9b-lbwns luna   File "/home/luna/.local/lib/python3.6/site-packages/flask_cors/__init__.py", line 279, in wrapped_function
luna-7995d99d9b-lbwns luna     return cors_after_request(app.make_response(f(*args, **kwargs)))
luna-7995d99d9b-lbwns luna   File "/home/luna/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
luna-7995d99d9b-lbwns luna     reraise(exc_type, exc_value, tb)
luna-7995d99d9b-lbwns luna   File "/home/luna/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
luna-7995d99d9b-lbwns luna     raise value
luna-7995d99d9b-lbwns luna   File "/home/luna/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
luna-7995d99d9b-lbwns luna     rv = self.dispatch_request()
luna-7995d99d9b-lbwns luna   File "/home/luna/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
luna-7995d99d9b-lbwns luna     return self.view_functions[rule.endpoint](**req.view_args)
luna-7995d99d9b-lbwns luna   File "/home/luna/luna/api/evaluation_api_rest.py", line 24, in newEval
luna-7995d99d9b-lbwns luna     evaluationApi.evaluate(ev)
luna-7995d99d9b-lbwns luna   File "/home/luna/luna/api/evaluation_api.py", line 130, in evaluate
luna-7995d99d9b-lbwns luna     task = executor.newEvalTask(ev)
luna-7995d99d9b-lbwns luna   File "/home/luna/luna/task/executor_base.py", line 101, in newEvalTask
luna-7995d99d9b-lbwns luna     taskId=str(ev.id)
luna-7995d99d9b-lbwns luna   File "/home/luna/.local/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 294, in __get__
luna-7995d99d9b-lbwns luna     return self.impl.get(instance_state(instance), dict_)
luna-7995d99d9b-lbwns luna   File "/home/luna/.local/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 725, in get
luna-7995d99d9b-lbwns luna     value = state._load_expired(state, passive)
luna-7995d99d9b-lbwns luna   File "/home/luna/.local/lib/python3.6/site-packages/sqlalchemy/orm/state.py", line 652, in _load_expired
luna-7995d99d9b-lbwns luna     self.manager.deferred_scalar_loader(self, toload)
luna-7995d99d9b-lbwns luna   File "/home/luna/.local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 1010, in load_scalar_attributes
luna-7995d99d9b-lbwns luna     only_load_props=attribute_names,
luna-7995d99d9b-lbwns luna   File "/home/luna/.local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 206, in load_on_ident
luna-7995d99d9b-lbwns luna     identity_token=identity_token,
luna-7995d99d9b-lbwns luna   File "/home/luna/.local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 286, in load_on_pk_identity
luna-7995d99d9b-lbwns luna     return q.one()
luna-7995d99d9b-lbwns luna   File "/home/luna/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3490, in one
luna-7995d99d9b-lbwns luna     ret = self.one_or_none()
luna-7995d99d9b-lbwns luna   File "/home/luna/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3459, in one_or_none
luna-7995d99d9b-lbwns luna     ret = list(self)
luna-7995d99d9b-lbwns luna   File "/home/luna/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
luna-7995d99d9b-lbwns luna     return self._execute_and_instances(context)
luna-7995d99d9b-lbwns luna   File "/home/luna/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
luna-7995d99d9b-lbwns luna     result = conn.execute(querycontext.statement, self._params)
luna-7995d99d9b-lbwns luna   File "/home/luna/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
luna-7995d99d9b-lbwns luna     return meth(self, multiparams, params)
luna-7995d99d9b-lbwns luna   File "/home/luna/.local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
luna-7995d99d9b-lbwns luna     return connection._execute_clauseelement(self, multiparams, params)
luna-7995d99d9b-lbwns luna   File "/home/luna/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
luna-7995d99d9b-lbwns luna     distilled_params,
luna-7995d99d9b-lbwns luna   File "/home/luna/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
luna-7995d99d9b-lbwns luna     e, statement, parameters, cursor, context
luna-7995d99d9b-lbwns luna   File "/home/luna/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
luna-7995d99d9b-lbwns luna     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
luna-7995d99d9b-lbwns luna   File "/home/luna/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
luna-7995d99d9b-lbwns luna     raise exception
luna-7995d99d9b-lbwns luna   File "/home/luna/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
luna-7995d99d9b-lbwns luna     cursor, statement, parameters, context
luna-7995d99d9b-lbwns luna   File "/home/luna/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
luna-7995d99d9b-lbwns luna     cursor.execute(statement, parameters)
luna-7995d99d9b-lbwns luna sqlalchemy.exc.InternalError: (psycopg2.errors.InFailedSqlTransaction) current transaction is aborted, commands ignored until end of transaction block
luna-7995d99d9b-lbwns luna 
luna-7995d99d9b-lbwns luna [SQL: SELECT evaluation.id AS evaluation_id, evaluation.model_id AS evaluation_model_id, evaluation.project_rev_id AS evaluation_project_rev_id, evaluation.name AS evaluation_name, evaluation.output_path AS evaluation_output_path, evaluation.exit_code AS evaluation_exit_code, evaluation.created_at AS evaluation_created_at, evaluation.finished_at AS evaluation_finished_at 
luna-7995d99d9b-lbwns luna FROM evaluation 
luna-7995d99d9b-lbwns luna WHERE evaluation.id = %(param_1)s]
luna-7995d99d9b-lbwns luna [parameters: {'param_1': 1}]
luna-7995d99d9b-lbwns luna (Background on this error at: http://sqlalche.me/e/13/2j85)
luna-7995d99d9b-lbwns luna INFO:Flask-Cors:CORS request from Origin:None, setting Access-Control-Allow-Origi
```

**Comment by Leemoonsoo** [comment]
fixed
